// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Svayam Infoware Pvt. Ltd.
/**
 * `gov upgrade --from <content>` runner — the fs-backed shell around the pure
 * overlay-sync engine. Walks the content source + the adopter workspace, plans
 * the migration, and (with --apply) writes it. Dry-run by default.
 */
import * as fs from "node:fs";
import * as path from "node:path";
import { parseManifest, expandEntries, planUpgrade, applyUpgrade, formatPlan } from "./upgrade-sync.js";

const SKIP = new Set([".git", "node_modules"]);

/** Relative file paths under `root` (skips .git / node_modules). */
function walk(root: string, rel = ""): string[] {
  const abs = path.join(root, rel);
  if (!fs.existsSync(abs)) return [];
  const out: string[] = [];
  for (const name of fs.readdirSync(abs)) {
    if (SKIP.has(name)) continue;
    const childRel = rel ? `${rel}/${name}` : name;
    const st = fs.statSync(path.join(root, childRel));
    if (st.isDirectory()) out.push(...walk(root, childRel));
    else out.push(childRel);
  }
  return out;
}

export interface UpgradeSyncResult { readonly code: number; readonly lines: readonly string[]; }

export function runUpgradeSync(contentDir: string, adopterDir: string, opts: { apply: boolean }): UpgradeSyncResult {
  const manifestPath = path.join(contentDir, "MANIFEST.yaml");
  if (!fs.existsSync(manifestPath)) return { code: 1, lines: [`gov upgrade: no MANIFEST.yaml under ${contentDir}`] };

  const manifest = parseManifest(fs.readFileSync(manifestPath, "utf8"));
  const entries = expandEntries(manifest, walk(contentDir));
  const readContent = (rel: string): string | null => {
    const p = path.join(contentDir, rel);
    return fs.existsSync(p) && fs.statSync(p).isFile() ? fs.readFileSync(p, "utf8") : null;
  };
  const readAdopter = (rel: string): string | null => {
    const p = path.join(adopterDir, rel);
    return fs.existsSync(p) && fs.statSync(p).isFile() ? fs.readFileSync(p, "utf8") : null;
  };
  const plan = planUpgrade(entries, { readContent, readAdopter, adopterPaths: () => walk(adopterDir) });

  if (!opts.apply) {
    return { code: 0, lines: ["gov upgrade — DRY RUN (no changes written):", "", ...formatPlan(plan), "", "Re-run with --apply to write these changes."] };
  }

  const res = applyUpgrade(plan, {
    readContent,
    readAdopter,
    writeAdopter: (rel, text) => {
      const p = path.join(adopterDir, rel);
      fs.mkdirSync(path.dirname(p), { recursive: true });
      fs.writeFileSync(p, text);
    },
    removeAdopter: (rel) => fs.rmSync(path.join(adopterDir, rel.replace(/\/$/, "")), { recursive: true, force: true }),
  });
  return {
    code: 0,
    lines: [
      `gov upgrade — applied ${res.applied.length} change(s)${res.skipped.length ? `, skipped ${res.skipped.length} conflict(s) for review:` : "."}`,
      ...res.skipped.map((s) => `  ! ${s} (org-customized — reconcile by hand)`),
    ],
  };
}

import { execFileSync } from "node:child_process";

function git(dir: string, args: string[]): string {
  return execFileSync("git", ["-C", dir, ...args], { encoding: "utf8", stdio: ["ignore", "pipe", "pipe"] }).trim();
}
function contentVersion(dir: string): string {
  const p = path.join(dir, "VERSION");
  return fs.existsSync(p) ? fs.readFileSync(p, "utf8").trim() : "latest";
}
function upgradePrBody(version: string, appliedCount: number, plan: ReturnType<typeof planUpgrade>): string {
  const of = (k: string) => plan.actions.filter((a) => a.kind === k).map((a) => a.dst);
  const conflicts = of("conflict");
  const retired = of("retire");
  return [
    `Syncs this gov workspace to framework content **${version}** — generated by \`gov upgrade\`.`,
    ``,
    `- ${appliedCount} file(s) created / updated / retired.`,
    retired.length ? `- Retired under the new layout: ${retired.map((r) => `\`${r}\``).join(", ")}` : ``,
    ``,
    conflicts.length ? `**Review these carefully** — they differed from the framework baseline and may hold your customizations. This branch applies the framework version; restore your edits per-file in the diff where needed:` : `No customized files were touched.`,
    ...conflicts.map((c) => `- \`${c}\``),
    ``,
    `Everything else is framework-owned. Edit anything in this branch, then merge when the diff looks right.`,
  ].filter((l) => l !== undefined).join("\n");
}

/** Create a gov-upgrade branch with the full plan applied, push it, open a PR. */
export function runUpgradePr(contentDir: string, adopterDir: string, opts: { branch?: string } = {}): UpgradeSyncResult {
  if (!fs.existsSync(path.join(contentDir, "MANIFEST.yaml"))) return { code: 1, lines: [`gov upgrade: no MANIFEST.yaml under ${contentDir}`] };
  try { git(adopterDir, ["rev-parse", "--git-dir"]); } catch { return { code: 1, lines: ["gov upgrade --pr: not a git repository (or no remote). Use --apply for an in-place migration instead."] }; }
  if (git(adopterDir, ["status", "--porcelain"])) return { code: 1, lines: ["gov upgrade --pr: working tree has uncommitted changes — commit or stash first."] };

  const version = contentVersion(contentDir);
  const branch = opts.branch ?? `gov-upgrade-${version}`;
  const base = git(adopterDir, ["rev-parse", "--abbrev-ref", "HEAD"]);

  const manifest = parseManifest(fs.readFileSync(path.join(contentDir, "MANIFEST.yaml"), "utf8"));
  const entries = expandEntries(manifest, walk(contentDir));
  const readContent = (rel: string): string | null => { const p = path.join(contentDir, rel); return fs.existsSync(p) && fs.statSync(p).isFile() ? fs.readFileSync(p, "utf8") : null; };
  const readAdopter = (rel: string): string | null => { const p = path.join(adopterDir, rel); return fs.existsSync(p) && fs.statSync(p).isFile() ? fs.readFileSync(p, "utf8") : null; };
  const plan = planUpgrade(entries, { readContent, readAdopter, adopterPaths: () => walk(adopterDir) });
  if (plan.actions.every((a) => a.kind === "same")) return { code: 0, lines: ["gov upgrade: workspace already matches content — nothing to do."] };

  try { git(adopterDir, ["checkout", "-b", branch]); } catch { return { code: 1, lines: [`gov upgrade --pr: branch '${branch}' already exists — delete it or pass --branch <name>.`] }; }
  const res = applyUpgrade(plan, {
    readContent, readAdopter,
    writeAdopter: (rel, t) => { const p = path.join(adopterDir, rel); fs.mkdirSync(path.dirname(p), { recursive: true }); fs.writeFileSync(p, t); },
    removeAdopter: (rel) => fs.rmSync(path.join(adopterDir, rel.replace(/\/$/, "")), { recursive: true, force: true }),
  }, { includeConflicts: true }); // the PR diff IS the review — apply everything

  git(adopterDir, ["add", "-A"]);
  git(adopterDir, ["commit", "-m", `gov upgrade: sync framework content to ${version}`]);
  try { git(adopterDir, ["push", "-u", "origin", branch]); } catch (e) { return { code: 1, lines: [`Applied on ${branch} but push failed: ${(e as Error).message.split("\n")[0]}`] }; }
  let prUrl: string;
  try {
    prUrl = execFileSync("gh", ["pr", "create", "--base", base, "--head", branch, "--title", `gov upgrade → framework content ${version}`, "--body", upgradePrBody(version, res.applied.length, plan)], { cwd: adopterDir, encoding: "utf8", stdio: ["ignore", "pipe", "pipe"] }).trim();
  } catch (e) {
    return { code: 0, lines: [`Pushed ${branch} (open the PR manually — gh failed): ${(e as Error).message.split("\n")[0]}`] };
  }
  return { code: 0, lines: [`Opened upgrade PR: ${prUrl}`, `  ${branch} → ${base} · ${res.applied.length} file(s) changed`, `  Review per-file; keep your customizations where the diff replaces them, then merge.`] };
}

import * as os from "node:os";

/** The published framework repo — the default template source. */
export const DEFAULT_TEMPLATE = "https://github.com/svayam-opensource/governed-agentic-dev-framework.git";

/**
 * Fetch publish/content from the template remote into a temp dir (sparse, shallow
 * — only publish/content is materialized). Returns the content dir + a cleanup fn.
 * `templateUrl` may be a URL or a local path (for testing).
 */
export function fetchTemplateContent(templateUrl: string, ref: string): { contentDir: string; cleanup: () => void } {
  const tmp = fs.mkdtempSync(path.join(os.tmpdir(), "gov-content-"));
  const cleanup = () => fs.rmSync(tmp, { recursive: true, force: true });
  try {
    execFileSync("git", ["clone", "--depth", "1", "--filter=blob:none", "--sparse", "--branch", ref, templateUrl, tmp], { stdio: ["ignore", "pipe", "pipe"] });
    execFileSync("git", ["-C", tmp, "sparse-checkout", "set", "publish/content"], { stdio: ["ignore", "pipe", "pipe"] });
  } catch (e) {
    cleanup();
    throw new Error(`could not fetch content from ${templateUrl}@${ref}: ${(e as Error).message.split("\n").pop()}`, { cause: e });
  }
  const contentDir = path.join(tmp, "publish", "content");
  if (!fs.existsSync(path.join(contentDir, "MANIFEST.yaml"))) {
    cleanup();
    throw new Error(`fetched ${templateUrl}@${ref} but publish/content/MANIFEST.yaml is not there`);
  }
  return { contentDir, cleanup };
}
