// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Svayam Infoware Pvt. Ltd.
/**
 * `gov app setup`, `gov app check` AND `gov app rotate` — the org's GitHub App, through which a code repository's check workflow
 * reads the governance repository (rule-model-design.md, "gov-repo access": a GitHub App installed on the org,
 * free on every plan; NO stopgap token).
 *
 *   setup   Creates the App with GitHub's App-MANIFEST flow: a one-shot loopback page auto-POSTs the manifest to
 *           the org's "new App" page, GitHub redirects back with a single-use code, and `gh api` converts the
 *           code into the App's credentials. The client id and the private key go straight into the two org
 *           Actions secrets the rendered workflow reads (`GOV_APP_CLIENT_ID`, `GOV_APP_PRIVATE_KEY`), the key on
 *           `gh`'s STDIN. Then it prints the install URL.
 *   check   Is the App there, installed on the org, able to read the governance repo's default branch, and are
 *           both secrets set? Each miss names the next step. `gov doctor` shows the same verdict as one row.
 *   rotate  A NEW key (generated by the person on the App's page — GitHub has no API for it) onto every repository
 *           that needs it: a repo added after setup, or a key that leaked. Names the old key to delete.
 *
 * WHERE THE SECRETS GO (secret-reach.ts; sandbox finding, svayam-e2e, 2026-10-07): on GitHub Free an org secret
 * never reaches a private repository. So setup and rotate write org secrets where they reach and REPOSITORY
 * secrets on the governance repo and each linked code repo that needs its own copy; check and doctor name each
 * repo that will not receive one.
 *
 * THE PRIVATE KEY NEVER TOUCHES DISK OR A LOG. It arrives on `gh`'s stdout (run-process never logs stdout), lives
 * in one local variable, and leaves on `gh secret set`'s stdin (run-process never logs input). It is never an
 * argument, never a line printed, never written to a file — org-config.yaml records the App's PUBLIC identity
 * (`services.github_app: { client_id, slug }`) and nothing else.
 *
 * Pure over injected ports (a `gh` runner, the loopback, file read/write, a line printer); main.ts wires them.
 */
import path from "node:path";
import { createHash, createPrivateKey, createPublicKey } from "node:crypto";
import type { CommandResult } from "./dispatch.js";
import { CODE_SHAPE, type StartLoopback } from "./app-loopback.js";
import { GOV_APP_SECRETS } from "../rules/checks/render-github.js";
import { runResult } from "../run-process.js";
import { checkSecretNeeds, readReach, writeSecrets, type SecretNeed } from "./secret-reach.js";
import { flagBool, flagStr } from "./args.js";
import type { LinkedRepos } from "./check-scope.js";

// ── ports ──────────────────────────────────────────────────────────────────────────────────────────────────

export interface GhOutcome { readonly status: number; readonly stdout: string; readonly stderr: string }
/** Run `gh` with these arguments; `input`, when given, is its STDIN. Never throws. */
export type GhRun = (args: readonly string[], input?: string) => GhOutcome;

/** The real `gh`, through the run-process chokepoint (logged: command, redacted args, exit — never stdout or stdin). */
export function ghRunner(pgm: string, timeoutMs?: number): GhRun {
  return (args, input) => runResult("gh", args, { pgm, fn: "gh", ...(input === undefined ? {} : { input }), ...(timeoutMs ? { timeoutMs } : {}) });
}

export interface AppConfig {
  /** The governance repository's working tree (where org-config.yaml lives). */
  readonly home: string;
  readonly githubOrg: string;
  readonly orgSlugLower: string;
  /** The governance repository's NAME (`org_gov_repo`). */
  readonly workspaceRepo: string;
  readonly defaultBranch: string;
}

export interface AppSetupDeps {
  readonly gh: GhRun;
  readonly loopback: StartLoopback;
  readonly readFile: (file: string) => string | null;
  readonly writeFile: (file: string, text: string) => void;
  /** Print a line NOW — the person must see the URL before gov waits on the browser. */
  readonly say: (line: string) => void;
  /** An unguessable `state` value. */
  readonly newState: () => string;
  readonly timeoutMs?: number;
  /**
   * The CODE repositories that need the App's secrets — the project board's linked repos (bare names). Absent or
   * unreadable: only the governance repo is covered, and the output says a repo added later needs `gov app rotate`.
   */
  readonly codeRepos?: () => LinkedRepos;
  /** `gov app rotate --key-from-stdin`: all of stdin. */
  readonly readStdin?: () => string;
  /** `gov app rotate --key-file`: the key file is deleted after use. */
  readonly removeFile?: (file: string) => void;
}

// ── the App's public identity in org-config.yaml ──────────────────────────────────────────────────────────

export interface AppIdentity {
  readonly clientId: string;
  readonly slug: string;
  /** The private key's PUBLIC fingerprint as GitHub shows it on the App page (`SHA256:…`) — names the key to delete. */
  readonly keyFingerprint?: string;
}

/**
 * The fingerprint GitHub shows for an App private key: base64(sha256(the public key, DER SPKI)) — GitHub's own
 * `openssl rsa -pubout -outform DER | openssl sha256 -binary | openssl base64`. Null when the text is not a key. Pure.
 */
export function keyFingerprint(pem: string): string | null {
  try {
    const der = createPublicKey(createPrivateKey(pem)).export({ type: "spki", format: "der" });
    return `SHA256:${createHash("sha256").update(der).digest("base64")}`;
  } catch {
    // Not a key gov can read: the caller says so; nothing of the text is repeated.
    return null;
  }
}

/** `services.github_app: { client_id, slug }`, or null when absent or empty. Pure. */
export function readGithubApp(text: string | null | undefined): AppIdentity | null {
  if (!text) return null;
  const lines = text.split(/\r?\n/);
  const s = lines.findIndex((l) => /^services:\s*(#.*)?$/.test(l));
  if (s === -1) return null;
  let inApp = false, appIndent = 0;
  const got: Record<string, string> = {};
  for (const line of lines.slice(s + 1)) {
    if (/^\S/.test(line)) break;
    const m = /^(\s+)([A-Za-z_]+):\s*(.*)$/.exec(line);
    if (!m) continue;
    const indent = m[1]!.length;
    if (m[2] === "github_app") { inApp = true; appIndent = indent; continue; }
    if (!inApp) continue;
    if (indent <= appIndent) { inApp = false; continue; }
    got[m[2]!] = m[3]!.replace(/\s+#.*$/, "").trim().replace(/^["']|["']$/g, "").trim();
  }
  if (!got.client_id || !got.slug) return null;
  return { clientId: got.client_id, slug: got.slug, ...(got.key_fingerprint ? { keyFingerprint: got.key_fingerprint } : {}) };
}

/**
 * `text` with `services.github_app` set to `id` — replacing any earlier block, adding `services:` if there is none.
 * Everything else in the file is left byte-for-byte. Pure.
 */
export function withGithubApp(text: string, id: AppIdentity): string {
  const block = ["  github_app:                # written by `gov app setup` — the App's public identity, never its key",
    `    client_id: "${id.clientId}"`, `    slug: "${id.slug}"`,
    ...(id.keyFingerprint ? [`    key_fingerprint: "${id.keyFingerprint}"   # the current private key, as the App page shows it`] : [])];
  const lines = text.split("\n");
  const s = lines.findIndex((l) => /^services:\s*(#.*)?$/.test(l));
  if (s === -1) {
    const body = text.endsWith("\n") || text === "" ? text : `${text}\n`;
    return `${body}services:\n${block.join("\n")}\n`;
  }
  // Drop an existing `github_app:` sub-block (its line and everything indented deeper beneath it).
  const out = lines.slice(0, s + 1);
  let i = s + 1, skipIndent = -1;
  for (; i < lines.length; i++) {
    const line = lines[i]!;
    if (/^\S/.test(line)) break;
    const indent = /^(\s*)/.exec(line)![1]!.length;
    if (skipIndent >= 0) {
      if (line.trim() === "" || indent > skipIndent) continue;
      skipIndent = -1;
    }
    if (/^\s+github_app:/.test(line)) { skipIndent = indent; continue; }
    out.push(line);
  }
  // At the end of the services block, before any blank lines that separate it from what follows.
  let at = out.length;
  while (at > s + 1 && out[at - 1]!.trim() === "") at--;
  out.splice(at, 0, ...block);
  return [...out, ...lines.slice(i)].join("\n");
}

// ── the manifest ──────────────────────────────────────────────────────────────────────────────────────────

export interface AppManifest {
  readonly name: string;
  readonly url: string;
  readonly description: string;
  readonly hook_attributes: { readonly url: string; readonly active: false };
  readonly redirect_url: string;
  readonly public: false;
  readonly default_permissions: Readonly<Record<string, "read">>;
  readonly default_events: readonly string[];
}

export const appName = (orgSlugLower: string): string => `gov-${orgSlugLower.toLowerCase()}`;

/** The App gov asks GitHub for: read the governance repo's contents, nothing else; no webhook; private. Pure. */
export function appManifest(cfg: AppConfig, redirectUrl: string): AppManifest {
  const home = `https://github.com/${cfg.githubOrg}/${cfg.workspaceRepo}`;
  return {
    name: appName(cfg.orgSlugLower),
    url: home,
    description: `Lets gov's checks in ${cfg.githubOrg}'s code repositories read the governance rules in ${cfg.workspaceRepo} (read-only).`,
    hook_attributes: { url: home, active: false },
    redirect_url: redirectUrl,
    public: false,
    default_permissions: { contents: "read", metadata: "read" },
    default_events: [],
  };
}

const esc = (s: string): string => s.replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "\"": "&quot;", "'": "&#39;" })[c]!);

/** Where GitHub takes an org App manifest. */
export const newAppUrl = (org: string, state: string): string =>
  `https://github.com/organizations/${encodeURIComponent(org)}/settings/apps/new?state=${encodeURIComponent(state)}`;

/** The one-shot page: a form that POSTs the manifest to GitHub, submitted on load. Pure. */
export function manifestPage(manifest: AppManifest, org: string, state: string): string {
  return [
    "<!doctype html><meta charset=utf-8><title>gov app setup</title>",
    `<form method="post" action="${esc(newAppUrl(org, state))}">`,
    `<input type="hidden" name="manifest" value="${esc(JSON.stringify(manifest))}">`,
    `<p>Taking you to GitHub to create <b>${esc(manifest.name)}</b> for ${esc(org)}…</p>`,
    "<noscript><button type=submit>Continue to GitHub</button></noscript></form>",
    "<script>document.forms[0].submit()</script>",
  ].join("\n");
}

export const installUrl = (slug: string): string => `https://github.com/apps/${slug}/installations/new`;

// ── gh's failures, sorted into what they mean ─────────────────────────────────────────────────────────────

/** `missing` and `forbidden` are answers from GitHub; `unknown` (no network, a timeout, anything else) is not. */
export function ghFailure(r: GhOutcome): "missing" | "forbidden" | "unknown" {
  const t = `${r.stderr}\n${r.stdout}`;
  if (/HTTP 404|Not Found/i.test(t)) return "missing";
  if (/HTTP 40[13]|Resource not accessible|must have admin|Must be an organization owner|requires? (the )?(admin:org|read:org)|insufficient/i.test(t)) return "forbidden";
  return "unknown";
}

const firstLine = (s: string): string => s.split(/\r?\n/).map((l) => l.trim()).find(Boolean)?.slice(0, 200) ?? "no output";

function json<T>(s: string): T | null {
  try { return JSON.parse(s) as T; } catch { /* not JSON — the caller treats it as no answer */ return null; }
}

// ── gov app setup ─────────────────────────────────────────────────────────────────────────────────────────

interface Conversion { id?: number; slug?: string; client_id?: string; pem?: string }

export async function appSetup(deps: AppSetupDeps, cfg: AppConfig): Promise<CommandResult> {
  if (!cfg.githubOrg || !cfg.orgSlugLower || !cfg.workspaceRepo) {
    return { code: 1, lines: ["app setup: org-config.yaml must name `github_org`, `org_slug_lower` and `org_gov_repo` — set them (gov setup), then run this again."] };
  }
  const org = cfg.githubOrg;
  const cfgFile = path.join(cfg.home, "org-config.yaml");
  const cfgText = deps.readFile(cfgFile);

  // Already done? An App recorded here that GitHub still knows is not created twice.
  const recorded = readGithubApp(cfgText);
  if (recorded && deps.gh(["api", `/apps/${recorded.slug}`]).status === 0) {
    return { code: 0, lines: [
      `app setup: ${org} already has its App, ${recorded.slug} (recorded in org-config.yaml). Run \`gov app check\` to see whether it works.`,
      "  A repository added since, or a key that leaked: `gov app rotate` puts a new key on every repo that needs it.",
      `  To replace it: delete it at https://github.com/organizations/${org}/settings/apps/${recorded.slug}, remove services.github_app from org-config.yaml, and run this again.`,
    ] };
  }

  const state = deps.newState();
  let session;
  try {
    session = await deps.loopback({ page: (redirect) => manifestPage(appManifest(cfg, redirect), org, state), state, timeoutMs: deps.timeoutMs ?? 10 * 60_000 });
  } catch (e) {
    return { code: 1, lines: [`app setup: could not open a local listener for GitHub's redirect (${(e as Error).message}). Nothing was created.`] };
  }
  deps.say(`Open this page in a browser ON THIS MACHINE, signed in to GitHub as an owner of ${org}:`);
  deps.say(`  ${session.url}`);
  deps.say(`It takes you to GitHub to create the App ${appName(cfg.orgSlugLower)} (read-only access to repository contents, no webhook). Keep this terminal open.`);
  let code: string;
  try {
    code = await session.code;
  } catch (e) {
    return { code: 1, lines: [`app setup: ${(e as Error).message} — nothing came back from GitHub, so nothing was stored. Run \`gov app setup\` again.`] };
  } finally {
    session.close();
  }
  if (!CODE_SHAPE.test(code)) return { code: 1, lines: ["app setup: GitHub's redirect carried no usable code. Nothing was stored. Run `gov app setup` again."] };

  // THE EXCHANGE. Its answer holds the private key: only fields are read from it, and it is never printed.
  const conv = deps.gh(["api", "-X", "POST", `/app-manifests/${code}/conversions`]);
  const app = conv.status === 0 ? json<Conversion>(conv.stdout) : null;
  if (!app || !app.slug || !app.client_id || !app.pem) {
    return { code: 1, lines: [
      `app setup: GitHub did not hand over the App's credentials (${conv.status === 0 ? "the answer was incomplete" : firstLine(conv.stderr)}).`,
      `  The code is single-use and expires after an hour. If the App was created anyway, delete it at https://github.com/organizations/${org}/settings/apps and run \`gov app setup\` again.`,
    ] };
  }
  const { slug, client_id: clientId } = app;
  // The one reference to the key: the conversion object drops it, and this const goes out of scope on return.
  const pem = app.pem;
  delete app.pem;

  const lines: string[] = [`Created the GitHub App ${slug} (client id ${clientId}) for ${org}.`];
  // WHERE THE SECRETS MUST LIVE (sandbox finding, svayam-e2e, 2026-10-07): on GitHub Free an org secret never
  // reaches a private repository. While gov holds the key, it writes the secrets everywhere they are needed.
  const placed = placeAppSecrets(deps, cfg, clientId, pem);
  lines.push(...placed.lines);
  const fingerprint = keyFingerprint(pem);
  recordIdentity(deps, cfgFile, cfgText, { clientId, slug, ...(fingerprint ? { keyFingerprint: fingerprint } : {}) }, lines);
  if (placed.failed) {
    lines.push(
      "  gov kept no copy of the private key. Fix the access named above, then put a fresh key everywhere with:",
      `    gov app rotate        (it shows where to generate the key: https://github.com/organizations/${org}/settings/apps/${slug})`,
    );
    return { code: 1, lines };
  }
  lines.push(
    "gov kept no copy of the key.",
    "",
    "Now install it — one step only an owner can do in the browser:",
    `  ${installUrl(slug)}`,
    `  Choose the ${org} organization, then "Only select repositories" → ${cfg.workspaceRepo}. The App needs no other repository.`,
    "Then confirm it works:  gov app check",
  );
  return { code: 0, lines };
}

/**
 * The repositories that need the App's secrets: the governance repo and the project's linked code repos, as
 * `owner/name`. The second value says why the code repos are missing, when they are.
 */
function appSecretRepos(deps: Pick<AppSetupDeps, "codeRepos">, cfg: AppConfig): { repos: string[]; unknown?: string } {
  const gov = `${cfg.githubOrg}/${cfg.workspaceRepo}`;
  const linked = deps.codeRepos?.();
  if (!linked) return { repos: [gov], unknown: "no project's code repositories were looked up" };
  if (!linked.ok) return { repos: [gov], unknown: linked.reason };
  return { repos: [gov, ...linked.names.map((n) => (n.includes("/") ? n : `${cfg.githubOrg}/${n}`))] };
}

/** Write GOV_APP_CLIENT_ID / GOV_APP_PRIVATE_KEY where they reach. The key goes on gh's stdin and nowhere else. */
function placeAppSecrets(deps: AppSetupDeps, cfg: AppConfig, clientId: string, pem: string): { lines: string[]; failed: boolean } {
  const { repos, unknown } = appSecretRepos(deps, cfg);
  const { reaches } = readReach(deps.gh, cfg.githubOrg, repos);
  const out = writeSecrets(deps.gh, cfg.githubOrg, reaches, [
    { name: GOV_APP_SECRETS.clientId, value: clientId },
    { name: GOV_APP_SECRETS.privateKey, value: pem },
  ]);
  if (unknown) {
    out.lines.push(`  The code repositories were not covered (${unknown}). On the Free plan a private code repo needs its own copy: run \`gov app rotate\` on the project branch once it is known — or whenever a repo is added.`);
  }
  return out;
}

function recordIdentity(deps: AppSetupDeps, file: string, text: string | null, id: AppIdentity, lines: string[]): void {
  if (text === null) {
    lines.push(`  org-config.yaml was not found at ${file}; add this under services: to record the App:`,
      "    github_app:", `      client_id: "${id.clientId}"`, `      slug: "${id.slug}"`);
    return;
  }
  deps.writeFile(file, withGithubApp(text, id));
  lines.push(`Recorded the App's public identity (client id, slug — never the key) in ${file} under services.github_app. NOT committed — land it by pull request.`);
}

// ── gov app rotate ────────────────────────────────────────────────────────────────────────────────────────

const PEM_SHAPE = /-----BEGIN (?:RSA )?PRIVATE KEY-----[\s\S]+-----END (?:RSA )?PRIVATE KEY-----/;

/**
 * `gov app rotate [--key-from-stdin | --key-file <path>]` — a NEW private key onto every repository that needs it
 * (a repo added after setup, or a key that leaked). GitHub has no API that makes an App key, so the person
 * generates it on the App's page; gov reads it once, writes the secrets, and keeps nothing: a key file is deleted
 * after use, and the output names the OLD key to delete on the App page.
 */
export async function appRotate(deps: AppSetupDeps, cfg: AppConfig, flags: Readonly<Record<string, string | boolean>>): Promise<CommandResult> {
  const org = cfg.githubOrg;
  const fromStdin = flagBool(flags, "key-from-stdin");
  const keyFile = flagStr(flags, "key-file");
  if (fromStdin && keyFile !== undefined) return { code: 2, lines: ["app rotate: give the key one way — --key-from-stdin or --key-file <path>, not both."] };
  const cfgFile = path.join(cfg.home, "org-config.yaml");
  const cfgText = deps.readFile(cfgFile);
  const recorded = readGithubApp(cfgText);
  if (!org || !recorded) {
    return { code: 1, lines: ["app rotate: org-config.yaml records no GitHub App (services.github_app) — run `gov app setup` first."] };
  }
  const page = `https://github.com/organizations/${org}/settings/apps/${recorded.slug}`;
  if (!fromStdin && keyFile === undefined) {
    return { code: 1, lines: [
      "app rotate: nothing rotated yet — gov needs a NEW private key, and GitHub has no API that makes one.",
      `  1. Open ${page} → "Private keys" → "Generate a private key". Your browser downloads a .pem file.`,
      "  2. Hand it to gov, one of:",
      "       gov app rotate --key-file <the downloaded .pem>     (gov deletes the file after use)",
      "       gov app rotate --key-from-stdin < <the downloaded .pem>",
      "  gov writes it to every repository that needs it, then tells you which old key to delete on that page.",
    ] };
  }

  let pem: string | null;
  if (fromStdin) {
    pem = deps.readStdin ? deps.readStdin() : null;
  } else {
    pem = deps.readFile(keyFile!);
    if (pem === null) return { code: 1, lines: [`app rotate: no file at ${keyFile}. Nothing was set.`] };
  }
  const fingerprint = pem !== null && PEM_SHAPE.test(pem) ? keyFingerprint(pem) : null;
  if (pem === null || fingerprint === null) {
    return { code: 1, lines: [`app rotate: ${fromStdin ? "stdin" : keyFile} is not a private key. Nothing was set${keyFile !== undefined ? ", and the file was left as it was" : ""}.`] };
  }

  const lines: string[] = [`Rotating the key of ${recorded.slug} (client id ${recorded.clientId}); the new key is ${fingerprint}.`];
  let placed: { lines: string[]; failed: boolean };
  try {
    placed = placeAppSecrets(deps, cfg, recorded.clientId, pem);
  } finally {
    // gov never keeps a key: the file it was handed is gone once used, whatever happened above.
    if (keyFile !== undefined) {
      let why = deps.removeFile ? "" : "gov was given no way to delete files here";
      try {
        deps.removeFile?.(keyFile);
      } catch (e) {
        why = (e as Error).message;
      }
      lines.push(why ? `  ✗ could not delete ${keyFile} (${why}) — delete it yourself now.` : `Deleted ${keyFile} — gov keeps no copy of the key.`);
    }
  }
  lines.push(...placed.lines);
  if (cfgText !== null) {
    deps.writeFile(cfgFile, withGithubApp(cfgText, { clientId: recorded.clientId, slug: recorded.slug, keyFingerprint: fingerprint }));
    lines.push(`Recorded the new key's fingerprint in ${cfgFile} (services.github_app.key_fingerprint). NOT committed — land it by pull request.`);
  }
  lines.push(
    "",
    "Now delete the OLD key, so it stops working:",
    `  ${page} → "Private keys" → delete ${recorded.keyFingerprint ? `the key ${recorded.keyFingerprint}` : `every key except ${fingerprint}`}.`,
  );
  if (placed.failed) {
    lines.splice(lines.length - 2, 2, "Keep the OLD key until every repository has the new one — some secrets were NOT set (✗ above).",
      "app rotate: fix the access named there, then run `gov app rotate` again with a new key.");
  }
  return { code: placed.failed ? 1 : 0, lines };
}

// ── gov app check ─────────────────────────────────────────────────────────────────────────────────────────

export type AppVerdict = "ok" | "fail" | "cannot-tell";

export interface AppCheckResult {
  readonly verdict: AppVerdict;
  /** One line: what is true, or the first thing to fix. */
  readonly summary: string;
  readonly lines: readonly string[];
  /** Each repository that will not receive a secret it needs (✗), or for which gov cannot tell (?) — `gov doctor`'s row. */
  readonly secrets?: { readonly fail: readonly string[]; readonly unsure: readonly string[]; readonly checked: number };
}

/** What `gov app check` also checks when it is given them: where the secrets must reach. */
export interface SecretScope {
  /** The project's linked code repositories (bare names), which need the App's secrets. */
  readonly codeRepos?: LinkedRepos;
  /** The approved model's key, which the governance repo needs when `models.ci_allowed` is true; null = none needed. */
  readonly modelKey?: string | null;
}

interface Installation {
  id?: number; app_slug?: string; client_id?: string; suspended_at?: string | null;
  repository_selection?: "all" | "selected"; permissions?: Record<string, string>;
}

/** Is the org's App there, installed, able to read the governance repo's default branch — and are both secrets set? */
export function appCheck(gh: GhRun, cfg: AppConfig, recorded: AppIdentity | null, scope?: SecretScope): AppCheckResult {
  if (!cfg.githubOrg || !cfg.workspaceRepo) {
    const s = "org-config.yaml names no `github_org` / `org_gov_repo` — set them (gov setup)";
    return { verdict: "fail", summary: s, lines: [`  ✗ ${s}`] };
  }
  const org = cfg.githubOrg, repo = cfg.workspaceRepo, full = `${org}/${repo}`;
  const slug = recorded?.slug || appName(cfg.orgSlugLower);
  const branch = cfg.defaultBranch || "main";
  const lines: string[] = [];
  const fails: string[] = [], unknowns: string[] = [];
  const pass = (s: string): void => { lines.push(`  ✓ ${s}`); };
  const fail = (s: string): void => { lines.push(`  ✗ ${s}`); fails.push(s); };
  const unsure = (s: string): void => { lines.push(`  ? cannot tell: ${s}`); unknowns.push(s); };
  /** Something this check does not verify, and says where it is verified instead. Not a ✓, not a failure. */
  const note = (s: string): void => { lines.push(`  · not verified here: ${s}`); };
  let selectedReach: string | null = null;
  let secrets: AppCheckResult["secrets"];
  const done = (): AppCheckResult => ({
    ...(secrets ? { secrets } : {}),
    verdict: fails.length ? "fail" : unknowns.length ? "cannot-tell" : "ok",
    summary: fails[0] ?? unknowns[0] ?? (selectedReach
      ? `${slug} is installed on ${org} (selected repositories), ${full}@${branch} exists, and both secrets are set; that it reaches ${full} is proven by the first code-repo check run`
      : `${slug} is installed on ${org}, reads ${full}@${branch}, and both secrets are set`),
    lines,
  });
  /** No answer at all from GitHub (offline, a timeout): every later question would be the same guess. */
  const offline = (what: string, r: GhOutcome): AppCheckResult => { unsure(`${what} — GitHub did not answer (${firstLine(r.stderr)}). Check the network and run \`gov app check\` again.`); return done(); };

  // 1 · THE INSTALLATION
  const ir = gh(["api", `/orgs/${org}/installations?per_page=100`]);
  if (ir.status !== 0 && ghFailure(ir) === "unknown") return offline(`whether ${slug} is installed on ${org}`, ir);
  if (ir.status !== 0) {
    unsure(`your gh login cannot list ${org}'s App installations (${firstLine(ir.stderr)}). An owner of ${org} can: run \`gov app check\` as one.`);
  } else {
    const all = json<{ installations?: Installation[] }>(ir.stdout)?.installations ?? [];
    const inst = all.find((i) => i.app_slug === slug || (!!recorded?.clientId && i.client_id === recorded.clientId));
    if (!inst) {
      const ar = gh(["api", `/apps/${slug}`]);
      if (ar.status === 0) fail(`the App ${slug} exists but is not installed on ${org} — install it on ${repo} only: ${installUrl(slug)}`);
      else if (ghFailure(ar) === "missing") fail(`${org} has no GitHub App ${slug} — run \`gov app setup\``);
      else return offline(`whether the App ${slug} exists`, ar);
    } else if (inst.suspended_at) {
      fail(`${slug} is installed on ${org} but SUSPENDED — unsuspend it at https://github.com/organizations/${org}/settings/installations/${inst.id}`);
    } else if (!["read", "write"].includes(inst.permissions?.contents ?? "")) {
      fail(`${slug} cannot read repository contents — on https://github.com/organizations/${org}/settings/apps/${slug}/permissions set Contents: Read-only, then accept the change at https://github.com/organizations/${org}/settings/installations/${inst.id}`);
    } else {
      pass(`${slug} is installed on ${org} with read access to contents`);
      // 2 · CAN IT REACH THE GOVERNANCE REPO?
      //
      // WHAT AN OWNER'S TOKEN CAN READ (sandbox finding, PRJ-121, 2026-10-07). This asked
      // /user/installations/{id}/repositories, which answers only a GitHub-App USER token — so with an ordinary
      // `gh` login it said "cannot tell" every time. /orgs/{org}/installations gives the installation's
      // repository_selection and nothing finer. "all" proves the reach. "selected" does not say WHICH, so gov
      // says so and names where it is proven: the code repo's check run mints the App's token for the governance
      // repo, and fails on that step if the App cannot reach it. Never a ✓ for something gov did not see.
      const settings = `https://github.com/organizations/${org}/settings/installations/${inst.id}`;
      if (inst.repository_selection === "all") {
        pass(`it reaches ${full} (it is installed on ALL of ${org}'s repositories; it needs only ${repo} — narrow it at ${settings})`);
      } else {
        selectedReach = `${slug} is installed on selected repositories, and GitHub does not show an owner which ones — `
          + `that it reaches ${full} is proven by the first code-repo check run (its App-token step fails if not). `
          + `To look now: ${settings}`;
        note(selectedReach);
      }
      // 3 · THE DEFAULT BRANCH IT WILL READ
      if (!fails.length) {
        const br = gh(["api", `/repos/${full}/branches/${encodeURIComponent(branch)}`, "--jq", ".name"]);
        if (br.status === 0) pass(`${full} has its default branch ${branch}, which the checks read`);
        else if (ghFailure(br) === "missing") fail(`${full} has no branch ${branch} — the checks read the rules from there; fix \`default_branch\` in org-config.yaml or push the branch`);
        else if (ghFailure(br) === "unknown") return offline(`whether ${full}@${branch} exists`, br);
        else unsure(`whether ${full}@${branch} exists (${firstLine(br.stderr)})`);
      }
    }
  }

  // 4 · THE TWO ORG SECRETS — names and visibility only; gh never shows a value.
  const sr = gh(["secret", "list", "--org", org, "--json", "name,visibility"]);
  let orgSecrets: { name?: string; visibility?: string }[] | null = null;
  if (sr.status !== 0 && ghFailure(sr) === "unknown") return offline(`whether ${org}'s secrets are set`, sr);
  if (sr.status === 0) orgSecrets = json<{ name?: string; visibility?: string }[]>(sr.stdout) ?? [];

  // 5 · WHERE THE SECRETS MUST REACH (sandbox finding, svayam-e2e, 2026-10-07): on GitHub Free an org secret is
  // never given to a private repository. Asked only when the caller names the repositories.
  let orgNeeded = true;
  const needs: SecretNeed[] = [];
  if (scope) {
    const govFull = full;
    const { repos, unknown } = appSecretRepos({ ...(scope.codeRepos ? { codeRepos: () => scope.codeRepos! } : {}) }, cfg);
    if (unknown) note(`the code repositories' App secrets — ${unknown}`);
    for (const repo of repos) {
      for (const name of [GOV_APP_SECRETS.clientId, GOV_APP_SECRETS.privateKey]) needs.push({ repo, name, fix: "gov app rotate (a new key onto every repo that needs it)" });
    }
    if (scope.modelKey) needs.push({ repo: govFull, name: scope.modelKey, fix: `gh secret set ${scope.modelKey} -R ${govFull}` });
    const { reaches } = readReach(gh, org, repos);
    orgNeeded = reaches.some((r) => r.reach !== "repo-required");
  }

  if (orgSecrets === null) {
    unsure(`whether ${org}'s Actions secrets are set (${firstLine(sr.stderr)}) — that needs an org owner with the admin:org scope: gh auth refresh -h github.com -s admin:org`);
  } else {
    for (const name of [GOV_APP_SECRETS.clientId, GOV_APP_SECRETS.privateKey]) {
      const s = orgSecrets.find((x) => x.name === name);
      if (!orgNeeded) { if (!s) note(`the ${org} org secret ${name} — on the Free plan it would reach none of these private repositories; each holds its own copy`); continue; }
      if (!s) fail(`the ${org} org secret ${name} is not set — run \`gov app setup\` again (or set it by hand: gh secret set ${name} --org ${org} --visibility all)`);
      else if ((s.visibility ?? "").toLowerCase() === "private") fail(`the org secret ${name} is visible to private repositories only — reset it with --visibility all (re-run \`gov app setup\`, or gh secret set ${name} --org ${org} --visibility all)`);
      else pass(`the org secret ${name} is set (${(s.visibility ?? "?").toLowerCase()})`);
    }
  }

  if (needs.length) {
    const r = checkSecretNeeds(gh, org, needs, orgSecrets === null ? null : orgSecrets.map((x) => x.name ?? ""));
    r.pass.forEach(pass);
    r.fail.forEach(fail);
    r.unsure.forEach(unsure);
    secrets = { fail: r.fail, unsure: r.unsure, checked: needs.length };
  }
  return done();
}

/**
 * `gov doctor`'s second row: EVERY repository that will not receive a secret it needs, each with its fix. Null when
 * the check did not look (no repositories named) or found nothing wrong.
 */
export function secretsDiagnostic(r: AppCheckResult): { name: string; status: "ok" | "warn"; detail: string } | null {
  if (!r.secrets) return null;
  const { fail, unsure, checked } = r.secrets;
  if (!fail.length && !unsure.length) return { name: "Secrets reach", status: "ok", detail: `all ${checked} needed secrets reach their repositories` };
  return { name: "Secrets reach", status: "warn", detail: [...fail, ...unsure.map((u) => `cannot tell ${u}`)].join("; ") };
}

/** `gov doctor`'s row — the same check, said in one line. `cannot-tell` is never `ok`. */
export function appDiagnostic(r: AppCheckResult): { name: string; status: "ok" | "warn"; detail: string } {
  if (r.verdict === "ok") return { name: "GitHub App", status: "ok", detail: r.summary };
  if (r.verdict === "cannot-tell") return { name: "GitHub App", status: "warn", detail: `cannot tell — ${r.summary}` };
  return { name: "GitHub App", status: "warn", detail: `${r.summary} (details: gov app check)` };
}

// ── the verb ─────────────────────────────────────────────────────────────────────────────────────────────

const USAGE = "usage: gov app <setup|check|rotate> [--key-from-stdin | --key-file <path>]";

export async function appCommand(positionals: readonly string[], flags: Readonly<Record<string, string | boolean>>, deps: AppSetupDeps, cfg: AppConfig, scope?: SecretScope): Promise<CommandResult> {
  const sub = positionals[0];
  if (sub === "setup") return appSetup(deps, cfg);
  if (sub === "rotate") return appRotate(deps, cfg, flags);
  if (sub === "check") {
    const r = appCheck(deps.gh, cfg, readGithubApp(deps.readFile(path.join(cfg.home, "org-config.yaml"))), scope);
    const tail = r.verdict === "ok" ? "app check: ok" : r.verdict === "fail" ? "app check: FAILED — fix the ✗ items above" : "app check: COULD NOT TELL — see the ? items above";
    return { code: r.verdict === "ok" ? 0 : 1, lines: [...r.lines, tail] };
  }
  return { code: 2, lines: [USAGE] };
}
