// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Svayam Infoware Pvt. Ltd.
/**
 * `gov check install --all` AND `gov check status` — the check workflow across a project's repositories
 * (rule-model-design.md Q14: a binding is rendered into each resource's own automation; P3 wave 3).
 *
 * SCOPE. The governance repository's working tree, and every CODE repository linked to the project — the board's
 * repositories (GitHub is the source of truth), at their clones `<agent_work_root>/<PROJECT_ID>/<repo>/`. The
 * project is the one the governance repo's branch names, or `--project <id>`.
 *
 * install --all WRITES ONLY ON A PROJECT OR TASK BRANCH of that project. A repository on its default branch (or any
 * other) is refused and the reason printed: gov never writes a default branch. It never commits or pushes; it ends
 * with the commands the person runs. Identical bytes are reported `unchanged` and not rewritten. A repository no rule
 * binds gets nothing; a workflow gov wrote there earlier is reported, and removed only with `--prune`.
 *
 * status compares each repository's installed workflow with what install would write now: in-sync, stale, missing,
 * or cannot-tell (not cloned, not a git working tree, the board unreadable) — never in-sync on a guess.
 *
 * Pure over injected readers and writers; main.ts wires them.
 */
import path from "node:path";
import { flagBool, flagStr } from "./args.js";
import type { CommandResult } from "./dispatch.js";
import { renderForRepo, type CheckVerbConfig, type CheckVerbDeps, type RuleSetLoad } from "./check-verb.js";
import { readGithubApp } from "./app-verb.js";
import { defaultRef, loadCheckRuleSet } from "../rules/checks/ruleset-io.js";
import { WORKFLOW_PATH } from "../rules/checks/render-github.js";
import { boardNumberFromBranch, boardNumberFromProjectId } from "../lifecycle/task.js";
import { isProjectDirName } from "../lifecycle/local-projects.js";
import { repoNameFromUrl } from "../lifecycle/repo.js";
import type { Board } from "../lifecycle/board.js";

/** The first line of every workflow gov renders — how a file gov wrote is told from one a person wrote. */
export const GENERATED_MARK = "# GENERATED by gov from the rule stores";

export type LinkedRepos = { readonly ok: true; readonly names: readonly string[] } | { readonly ok: false; readonly reason: string };

export interface ScopeDeps {
  /** The CODE repositories linked to board #n — the board's repositories, the governance repo left out. */
  readonly linkedRepos: (boardNumber: number) => LinkedRepos;
  readonly pathExists: (p: string) => boolean;
  readonly listDir: (dir: string) => readonly string[];
  readonly removeFile: (p: string) => void;
}

/** {@link ScopeDeps.linkedRepos} over a {@link Board}: one read of the board, its repositories by name. */
export function boardLinkedRepos(board: Board, githubOrg: string, workspaceRepo: string): ScopeDeps["linkedRepos"] {
  return (number) => {
    try {
      const b = board.fetchProject({ owner: githubOrg, ownerField: "organization", number });
      return { ok: true, names: [...new Set(b.repoUrls.map(repoNameFromUrl))].filter((n) => n !== workspaceRepo).sort() };
    } catch (e) {
      return { ok: false, reason: `the board could not be read (${(e as Error).message})` };
    }
  };
}

interface Target { readonly name: string; readonly dir: string; readonly gov: boolean }
interface Scope {
  readonly label: string;
  readonly boardNumber: number | null;
  readonly targets: readonly Target[];
  /** Why the code repositories are not in `targets`: no project, or the board could not be read. */
  readonly codeUnknown?: string;
}

const branchOf = (deps: CheckVerbDeps, dir: string): string | null =>
  deps.git(dir, ["symbolic-ref", "--quiet", "--short", "HEAD"])?.trim() || null;

function resolveScope(flags: Readonly<Record<string, string | boolean>>, deps: CheckVerbDeps, scope: ScopeDeps, cfg: CheckVerbConfig): Scope | { error: string } {
  const projectFlag = flagStr(flags, "project");
  let govDir: string, projectDir: string, boardNumber: number | null, label: string;
  if (projectFlag !== undefined) {
    boardNumber = boardNumberFromProjectId(projectFlag);
    if (boardNumber === null) return { error: `'${projectFlag}' is not a project id (PRJ-<n>-<slug>, or the board number)` };
    if (!cfg.agentWorkRoot) return { error: "the work root is unknown (org-config.yaml names no org_slug), so the project's clones cannot be found" };
    const n = boardNumber;
    const dirs = scope.listDir(cfg.agentWorkRoot).filter((d) => isProjectDirName(d) && boardNumberFromProjectId(d) === n);
    const name = dirs.includes(projectFlag) ? projectFlag : dirs.length === 1 ? dirs[0]! : null;
    if (!name) return { error: `no single clone of project #${n} under ${cfg.agentWorkRoot}${dirs.length ? ` (found ${dirs.join(", ")} — name one)` : " — `gov join` clones it"}` };
    projectDir = path.join(cfg.agentWorkRoot, name);
    govDir = path.join(projectDir, cfg.workspaceRepo);
    label = name;
  } else {
    govDir = path.resolve(cfg.home);
    projectDir = path.dirname(govDir);
    const branch = branchOf(deps, govDir);
    boardNumber = branch ? boardNumberFromBranch(branch) : null;
    label = boardNumber === null ? "no active project" : isProjectDirName(path.basename(projectDir)) ? path.basename(projectDir) : `project #${boardNumber}`;
  }
  const targets: Target[] = [{ name: cfg.workspaceRepo || path.basename(govDir), dir: govDir, gov: true }];
  if (boardNumber === null) {
    return { label, boardNumber, targets, codeUnknown: "no active project — the governance repo is not on a project branch; pass --project <id>" };
  }
  const linked = scope.linkedRepos(boardNumber);
  if (!linked.ok) return { label, boardNumber, targets, codeUnknown: `cannot tell which code repos are linked — ${linked.reason}` };
  for (const name of linked.names) targets.push({ name, dir: path.join(projectDir, name), gov: false });
  return { label, boardNumber, targets };
}

/** Why a repository cannot be judged at all (not cloned, not git), or null. */
function unreadable(t: Target, scope: ScopeDeps): string | null {
  if (!scope.pathExists(t.dir)) return `not cloned at ${t.dir} — \`gov join\` clones the project's repos`;
  if (!scope.pathExists(path.join(t.dir, ".git"))) return `${t.dir} is not a git working tree`;
  return null;
}

/** Why install refuses to write `t`, or null when its current branch is this project's project or task branch. */
function refusal(t: Target, deps: CheckVerbDeps, scope: ScopeDeps, boardNumber: number | null): { why: string } | { branch: string } {
  const bad = unreadable(t, scope);
  if (bad) return { why: bad };
  const branch = branchOf(deps, t.dir);
  if (!branch) return { why: "HEAD is detached (or git could not read the branch) — check out the project or task branch" };
  const n = boardNumberFromBranch(branch);
  if (n === null) return { why: `on \`${branch}\`, not a project or task branch — gov never writes a default branch; check out the project branch first` };
  if (boardNumber !== null && n !== boardNumber) return { why: `on \`${branch}\`, a branch of another project (#${n})` };
  return { branch };
}

const pad = (s: string, n: number): string => (s.length >= n ? `${s} ` : s + " ".repeat(n - s.length));

function loadRules(deps: CheckVerbDeps, cfg: CheckVerbConfig): { ref: string; loaded: RuleSetLoad } {
  const ref = defaultRef(deps.git, cfg.home, cfg.defaultBranch);
  return { ref, loaded: loadCheckRuleSet(deps.git, cfg.home, ref) };
}

// ── install --all ────────────────────────────────────────────────────────────────────────────────────────

type Outcome = "written" | "unchanged" | "removed" | "refused" | "stale" | "nothing";

export function checkInstallAll(flags: Readonly<Record<string, string | boolean>>, deps: CheckVerbDeps, cfg: CheckVerbConfig): CommandResult {
  const scope = deps.scope;
  if (!scope) return { code: 1, lines: ["check install --all: this build cannot read the project's repositories. Nothing was written."] };
  const s = resolveScope(flags, deps, scope, cfg);
  if ("error" in s) return { code: 1, lines: [`check install --all: ${s.error}. Nothing was written.`] };
  const { ref, loaded } = loadRules(deps, cfg);
  if (!loaded.ok) return { code: 1, lines: [`check install --all: the rules could not be read at ${ref}: ${loaded.reason}. Nothing was written.`] };
  const prune = flagBool(flags, "prune");

  const lines: string[] = [`gov check install --all — ${s.label}, rules from ${ref}`];
  // The App first: a code repo's workflow written now fails at its token step until the org has one.
  if (s.targets.some((t) => !t.gov) && !readGithubApp(deps.readFile(path.join(cfg.home, "org-config.yaml")))) {
    lines.push(`! No GitHub App is recorded (services.github_app in org-config.yaml): code repos' workflows will fail at the token step until an org owner runs \`gov app setup\`.`);
  }
  const done: { t: Target; outcome: Outcome; branch: string }[] = [];
  let refused = 0;
  const row = (outcome: Outcome | "cannot tell", name: string, detail: string): void => { lines.push(`  ${pad(outcome, 11)}${pad(name, 16)}${detail}`); };

  for (const t of s.targets) {
    const r = refusal(t, deps, scope, s.boardNumber);
    if ("why" in r) { refused++; row("refused", t.name, r.why); continue; }
    const rendered = renderForRepo(t.gov, loaded, cfg);
    if (!rendered.ok) { refused++; row("refused", t.name, rendered.reason); continue; }
    const abs = path.join(t.dir, WORKFLOW_PATH);
    const current = deps.readFile(abs);
    if (!rendered.files.length) {
      if (current === null) { row("nothing", t.name, "no rule in force binds a check GitHub can run here — nothing to write"); continue; }
      if (!current.startsWith(GENERATED_MARK)) { row("nothing", t.name, `no rule binds it; ${WORKFLOW_PATH} was not written by gov, left alone`); continue; }
      if (!prune) { row("stale", t.name, `no rule binds it now, but gov wrote ${WORKFLOW_PATH} earlier — re-run with --prune to remove it`); continue; }
      scope.removeFile(abs);
      row("removed", t.name, `${abs} (on ${r.branch})`);
      done.push({ t, outcome: "removed", branch: r.branch });
      continue;
    }
    for (const f of rendered.files) {
      const file = path.join(t.dir, f.path);
      if (deps.readFile(file) === f.text) { row("unchanged", t.name, file); continue; }
      deps.writeFile(file, f.text);
      row("written", t.name, `${file} (on ${r.branch}, ${rendered.bindings.length} binding(s))`);
      done.push({ t, outcome: "written", branch: r.branch });
    }
  }
  if (s.codeUnknown) { refused++; row("cannot tell", "code repos", s.codeUnknown); }

  if (done.length) lines.push("", ...landing(done, cfg));
  else lines.push("", "Nothing changed on disk, so there is nothing to commit.");
  return { code: refused ? 1 : 0, lines };
}

/** The commands the person runs — gov committed and pushed nothing. */
function landing(done: readonly { t: Target; outcome: Outcome; branch: string }[], cfg: CheckVerbConfig): string[] {
  const out = ["NOT committed and NOT pushed. Review the diff, then:"];
  for (const { t, outcome, branch } of done) {
    out.push(
      `  git -C ${t.dir} add ${WORKFLOW_PATH}`,
      `  git -C ${t.dir} commit -m "gov-checks: ${outcome === "removed" ? "remove the workflow no rule binds" : "install the rendered check workflow"}"`,
      `  git -C ${t.dir} push origin ${branch}`,
    );
  }
  // A task branch lands with `gov merge` (every repo at once); a project branch by its own pull request.
  const tasks = [...new Set(done.map((d) => d.branch).filter((b) => b.includes(".ISSUE-")))].sort();
  const direct = done.filter((d) => !d.branch.includes(".ISSUE-"));
  if (tasks.length) out.push("then land the task branch (it merges every repo that has it):", ...tasks.map((b) => `  gov merge ${b}`));
  if (direct.length) {
    out.push("then open the pull request for each project branch:");
    for (const { t, branch } of direct) {
      const repo = cfg.githubOrg ? `${cfg.githubOrg}/${t.gov ? cfg.workspaceRepo : t.name}` : t.name;
      const base = t.gov ? cfg.defaultBranch : cfg.defaultCodeBranch;
      out.push(`  gh pr create --repo ${repo} --base ${base} --head ${branch} --title "gov-checks: install the check workflow" --body "Rendered by gov check install --all."`);
    }
  }
  return out;
}

// ── status ───────────────────────────────────────────────────────────────────────────────────────────────

export type SyncState = "in-sync" | "stale" | "missing" | "cannot tell";
export interface StatusRow { readonly name: string; readonly state: SyncState; readonly detail: string }
export type StatusReport = { readonly ok: true; readonly label: string; readonly ref: string; readonly rows: readonly StatusRow[] } | { readonly ok: false; readonly reason: string };

/** Each repository in scope, its installed workflow against what install would write now. Writes nothing. */
export function checkStatusReport(flags: Readonly<Record<string, string | boolean>>, deps: CheckVerbDeps, cfg: CheckVerbConfig): StatusReport {
  const scope = deps.scope;
  if (!scope) return { ok: false, reason: "this build cannot read the project's repositories" };
  if (deps.git(cfg.home, ["rev-parse", "--is-inside-work-tree"])?.trim() !== "true") return { ok: false, reason: `${cfg.home} is not a git working tree` };
  const s = resolveScope(flags, deps, scope, cfg);
  if ("error" in s) return { ok: false, reason: s.error };
  const { ref, loaded } = loadRules(deps, cfg);
  if (!loaded.ok) return { ok: false, reason: `the rules could not be read at ${ref}: ${loaded.reason}` };
  const rows: StatusRow[] = [];
  for (const t of s.targets) {
    const bad = unreadable(t, scope);
    if (bad) { rows.push({ name: t.name, state: "cannot tell", detail: bad }); continue; }
    const rendered = renderForRepo(t.gov, loaded, cfg);
    if (!rendered.ok) { rows.push({ name: t.name, state: "cannot tell", detail: rendered.reason }); continue; }
    const current = deps.readFile(path.join(t.dir, WORKFLOW_PATH));
    const want = rendered.files[0]?.text ?? null;
    if (want === null) {
      rows.push(current !== null && current.startsWith(GENERATED_MARK)
        ? { name: t.name, state: "stale", detail: "no rule binds it now, but a workflow gov wrote is still there — `gov check install --all --prune`" }
        : { name: t.name, state: "in-sync", detail: "no rule binds it; nothing installed" });
    } else if (current === null) {
      rows.push({ name: t.name, state: "missing", detail: `no ${WORKFLOW_PATH}; ${rendered.bindings.length} binding(s) want one — \`gov check install --all\`` });
    } else if (current === want) {
      rows.push({ name: t.name, state: "in-sync", detail: WORKFLOW_PATH });
    } else {
      rows.push({ name: t.name, state: "stale", detail: "differs from what install would write now — `gov check install --all`" });
    }
  }
  if (s.codeUnknown) rows.push({ name: "code repos", state: "cannot tell", detail: s.codeUnknown });
  return { ok: true, label: s.label, ref, rows };
}

export function checkStatus(flags: Readonly<Record<string, string | boolean>>, deps: CheckVerbDeps, cfg: CheckVerbConfig): CommandResult {
  const r = checkStatusReport(flags, deps, cfg);
  if (!r.ok) return { code: 1, lines: [`check status: cannot tell — ${r.reason}.`] };
  const lines = [`gov check status — ${r.label}, rules from ${r.ref}`, ...r.rows.map((x) => `  ${pad(x.state, 12)}${pad(x.name, 16)}${x.detail}`)];
  return { code: r.rows.every((x) => x.state === "in-sync") ? 0 : 1, lines };
}

/** `gov doctor`'s one row. Anything short of every repo in sync is a warning; cannot-tell is never ok. */
export function checksDiagnostic(r: StatusReport): { name: string; status: "ok" | "warn"; detail: string } {
  const name = "gov-checks";
  if (!r.ok) return { name, status: "warn", detail: `cannot tell — ${r.reason}` };
  const off = r.rows.filter((x) => x.state !== "in-sync");
  if (!off.length) return { name, status: "ok", detail: `in sync in ${r.rows.length} repo(s) (${r.label})` };
  const by = (st: SyncState) => off.filter((x) => x.state === st).map((x) => x.name);
  const parts = (["stale", "missing", "cannot tell"] as const).filter((st) => by(st).length).map((st) => `${st}: ${by(st).join(", ")}`);
  return { name, status: "warn", detail: `${parts.join("; ")} — details: gov check status` };
}
