#!/usr/bin/env bash
# Script: close-knowledge
# Purpose: Synthesizes project knowledge into org knowledge proposals using LLM+RAG.
#          Raises PR for domain owner review.
# Usage:   bash close-knowledge.sh <project_id>
# Triggered by: close-project automatically after successful project close.
# Compliance: C02 (POL-097 to POL-106)
#
# LLM synthesis note:
#   This script prepares the branch and context, then invokes the agent (Claude Code)
#   to perform synthesis. The agent reads all project knowledge, queries relevant org
#   knowledge, and proposes changes via the knowledge-close branch.
#   If the agent is not available, the script falls back to creating the PR with raw
#   project knowledge attached for manual review.

set -euo pipefail
source "$(dirname "$0")/lib.sh"
load_config

# ── Inputs ────────────────────────────────────────────────────────────────────

PROJECT_ID="${1:-}"
[[ -n "$PROJECT_ID" ]] || hard_stop "Usage: $0 <project_id>"

echo "=== close-knowledge: $PROJECT_ID"
echo ""

PROJECT_YAML=$(get_project_yaml "$PROJECT_ID")
PROJECT_DIR=$(get_project_dir "$PROJECT_ID")
check_project_exists "$PROJECT_ID"

# ── Pre-conditions ────────────────────────────────────────────────────────────

require_project_status "$PROJECT_YAML" "completed"

KNOWLEDGE_DIR="$PROJECT_DIR/knowledge"
if [[ ! -d "$KNOWLEDGE_DIR" ]] || [[ -z "$(find "$KNOWLEDGE_DIR" -type f 2>/dev/null)" ]]; then
  hard_stop "projects/$PROJECT_ID/knowledge/ is empty — nothing to synthesize."
fi

BRANCH="${ORG_SLUG_LOWER}-$(echo "$PROJECT_ID" | sed "s/^${ORG_SLUG}-//")"
KNOWLEDGE_BRANCH="${BRANCH}-knowledge"
TODAY=$(today)

# ── Create knowledge branch ───────────────────────────────────────────────────

echo "Creating knowledge branch '$KNOWLEDGE_BRANCH'..."
cd "$REPO_ROOT"
git fetch origin "$DEFAULT_BRANCH"
git checkout "$DEFAULT_BRANCH"
git pull origin "$DEFAULT_BRANCH"

if git rev-parse --verify "$KNOWLEDGE_BRANCH" &>/dev/null; then
  hard_stop "Branch '$KNOWLEDGE_BRANCH' already exists — investigate before proceeding."
fi
git checkout -b "$KNOWLEDGE_BRANCH"

# ── Collect project knowledge ─────────────────────────────────────────────────

echo "Collecting project knowledge from $KNOWLEDGE_DIR..."

KNOWLEDGE_SUMMARY_FILE="$REPO_ROOT/.close-knowledge-context-$PROJECT_ID.md"

{
  echo "# Knowledge Close Context: $PROJECT_ID"
  echo ""
  echo "**Project:** $PROJECT_ID"
  echo "**Closed:** $TODAY"
  echo "**Knowledge dir:** projects/$PROJECT_ID/knowledge/"
  echo ""
  echo "---"
  echo ""
  echo "## Project Knowledge Files"
  echo ""
  find "$KNOWLEDGE_DIR" -type f | sort | while IFS= read -r f; do
    rel="${f#$REPO_ROOT/}"
    echo "### $rel"
    echo ""
    cat "$f"
    echo ""
    echo "---"
    echo ""
  done
} > "$KNOWLEDGE_SUMMARY_FILE"

info "Context written to: $KNOWLEDGE_SUMMARY_FILE"

# ── LLM synthesis step ────────────────────────────────────────────────────────
#
# The agent (Claude Code) running this script should now:
#   1. Read all files in $KNOWLEDGE_DIR
#   2. Read relevant org knowledge in $REPO_ROOT/knowledge/ for RAG context
#   3. Synthesize: map project learnings → org knowledge locations
#   4. Apply proposed changes to knowledge/ on this branch
#   5. Call: bash close-knowledge.sh <project_id> --finalize <pr_description_file>
#
# If the agent is not available, we fall back to attaching raw knowledge.

if [[ "${2:-}" == "--finalize" ]]; then
  # Phase 2: agent has done synthesis and calls us back to create the PR
  PR_DESC_FILE="${3:-}"
  [[ -n "$PR_DESC_FILE" && -f "$PR_DESC_FILE" ]] \
    || hard_stop "--finalize requires a PR description file as argument 3."
  PR_BODY=$(cat "$PR_DESC_FILE")
  _finalize_mode=true
else
  # Phase 1: no agent synthesis — fall back to attaching raw knowledge for manual review
  warn "LLM synthesis not performed — attaching raw project knowledge for manual review."
  PR_BODY=$(cat <<MD
## Knowledge Close: $PROJECT_ID

**Automated synthesis was not performed.** This PR attaches the raw project knowledge
for manual review by domain owners.

### Project Knowledge

See \`projects/$PROJECT_ID/knowledge/\` in this branch for all captured learnings.

### Review Instructions

Domain owners: please review the project knowledge and manually apply relevant
learnings to the appropriate \`knowledge/\` subfolders in this PR.

*Generated by close-knowledge.sh — fallback mode (no LLM synthesis)*
MD
)
  _finalize_mode=false
fi

# ── Commit knowledge changes to branch ───────────────────────────────────────

# Remove temp context file
rm -f "$KNOWLEDGE_SUMMARY_FILE"

# Stage any knowledge/ changes the agent may have made
git add "knowledge/" 2>/dev/null || true

# If no changes were staged (fallback mode), there is nothing new to commit;
# the PR will just carry the branch with existing org knowledge as baseline.
if git diff --cached --quiet; then
  info "No knowledge/ changes staged — PR will describe manual review needed."
  # Create a placeholder note so the branch has at least one commit
  mkdir -p "$REPO_ROOT/knowledge/accumulated"
  cat >> "$REPO_ROOT/knowledge/accumulated/README.md" <<NOTE

<!-- close-knowledge: $PROJECT_ID — manual review needed ($TODAY) -->
NOTE
  git add "knowledge/accumulated/README.md"
fi

git commit -m "close-knowledge: $PROJECT_ID" --allow-empty
git push -u origin "$KNOWLEDGE_BRANCH"

# ── Raise PR ──────────────────────────────────────────────────────────────────

echo "Raising PR: $KNOWLEDGE_BRANCH → $DEFAULT_BRANCH..."

PR_URL=$(gh pr create \
  --base "$DEFAULT_BRANCH" \
  --head "$KNOWLEDGE_BRANCH" \
  --title "[Knowledge Close] $PROJECT_ID" \
  --body "$PR_BODY" \
  2>/dev/null) \
  || {
    warn "PR creation failed — retrying..."
    PR_URL=$(gh pr create \
      --base "$DEFAULT_BRANCH" \
      --head "$KNOWLEDGE_BRANCH" \
      --title "[Knowledge Close] $PROJECT_ID" \
      --body "$PR_BODY")
  }

info "PR created: $PR_URL"

# ── Update project.yaml ───────────────────────────────────────────────────────

cd "$REPO_ROOT"
git checkout "$DEFAULT_BRANCH"
git pull origin "$DEFAULT_BRANCH"

yaml_set "$PROJECT_YAML" "knowledge_status" "pending_review"
yaml_set "$PROJECT_YAML" "knowledge_pr"     "$PR_URL"

git add "projects/$PROJECT_ID/project.yaml"
git commit -m "close-knowledge: update knowledge_status for $PROJECT_ID"
git push origin "$DEFAULT_BRANCH"

echo ""
echo "=== Knowledge close initiated."
echo "    Branch:           $KNOWLEDGE_BRANCH"
echo "    PR:               $PR_URL"
echo "    knowledge_status: pending_review"
echo ""
echo "    CODEOWNERS will auto-assign domain reviewers."
echo "    Outcome updates:"
echo "      Merged   → archive tag + delete branch, knowledge_status: merged"
echo "      Rejected → owner closes PR, knowledge_status: rejected"
