// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Svayam Infoware Pvt. Ltd.
/**
 * THE RULE MAP — TWO STORES, ONE VIEW (rule-model-design.md Q5, Q8, Q15, Q22; 2026-10-06).
 *
 * `rule-map.md` is the generated, merged view over the framework's store and the org's: one row per REVISION, so a
 * rule's history is visible (a closed row shows when it stopped; the open row has no End). Its class is derived by
 * `classifyRow`, never stored, so the view cannot drift from the rows and the catalog.
 *
 * Pure and byte-stable: the same RuleSet renders the same bytes whatever order the rows arrive in.
 */
import { classifyRow, type RuleClass } from "./catalog.js";
import type { RuleSet } from "./contracts.js";
import { parseGovId, FRAMEWORK_SCOPE } from "./gov-id.js";
import { compareVersions, inForce, type RuleRow, type Stamp } from "./rule-row.js";

/**
 * What each class means, in the order the legend shows them. `satisfies` makes the compiler refuse a RuleClass
 * this legend does not explain; a test reads catalog.ts and refuses the same at run time.
 */
export const RULE_CLASS_LEGEND = {
  prevented: "a check on a gate event refuses the violation, so it cannot land",
  detected: "a check on an observe event notices the violation after it has landed",
  judged: "an LLM judge reviews it after the fact; a human confirms or dismisses each finding, and it never blocks",
  cued: "no check; the agent is reminded by a cue, and nothing verifies it was followed",
  advisory: "no check and no cue; nothing enforces it",
  "cannot-tell": "it claims a check, but no bound resource can listen yet, so nothing runs",
} as const satisfies Record<RuleClass, string>;

const CLASSES = Object.keys(RULE_CLASS_LEGEND) as RuleClass[];
const CUE_CHARS = 60;

/** Per-class counts over the rows IN FORCE in both stores; closed revisions and retired rules do not count. */
export function summariseRuleSet(rs: RuleSet): Record<RuleClass, number> {
  const counts = Object.fromEntries(CLASSES.map((k) => [k, 0])) as Record<RuleClass, number>;
  for (const r of inForce([...rs.framework, ...rs.org])) counts[classifyRow(r, rs.catalog)]++;
  return counts;
}

const isFramework = (r: RuleRow): boolean => parseGovId(r.id)?.scope === FRAMEWORK_SCOPE;

/** Framework first, then scope, then id number, then start version (then end, so a malformed store still sorts stably). */
function compareRows(a: RuleRow, b: RuleRow): number {
  const fa = isFramework(a), fb = isFramework(b);
  if (fa !== fb) return fa ? -1 : 1;
  const ga = parseGovId(a.id), gb = parseGovId(b.id);
  const sa = ga?.scope ?? a.id, sb = gb?.scope ?? b.id;
  if (sa !== sb) return sa < sb ? -1 : 1;
  const n = (ga?.n ?? 0) - (gb?.n ?? 0);
  if (n) return n;
  if (a.id !== b.id) return a.id < b.id ? -1 : 1;
  const v = compareVersions(a.start.version, b.start.version);
  if (v) return v;
  if (a.end === null || b.end === null) return a.end === b.end ? 0 : a.end === null ? 1 : -1;
  return compareVersions(a.end.version, b.end.version);
}

/** One cell: `|` escaped, line breaks flattened, so a row stays a single table row. */
const cell = (s: string): string => s.replace(/\r?\n/g, " ").replace(/\|/g, "\\|").trim();

const stamp = (s: Stamp | null): string => (s ? `${s.version} (${s.date})${s.pr === undefined ? "" : ` #${s.pr}`}` : "");

const cue = (r: RuleRow): string => {
  if (!r.cue) return "";
  const t = r.cue.text.replace(/\s+/g, " ").trim();
  return `${r.cue.tier}: ${t.length > CUE_CHARS ? `${t.slice(0, CUE_CHARS)}…` : t}`;
};

const checks = (r: RuleRow): string => (r.checks ?? []).map((c) => `${c.on.resource}·${c.on.event} → ${c.action}`).map(cell).join("<br>");

function line(r: RuleRow, rs: RuleSet): string {
  const fw = isFramework(r);
  return `| ${[
    r.id,
    r.source.doc,
    fw ? "Specification" : "Policy",
    `§${r.source.section}`,
    fw ? "framework" : "organization",
    r.level,
    r.expectation,
    r.actor.join(", "),
    cue(r),
    checks(r),
    classifyRow(r, rs.catalog),
    stamp(r.start),
    stamp(r.end),
  ].map((c, i) => (i === 9 ? c : cell(c))).join(" | ")} |`;
}

/** `rule-map.md`: every revision of every rule in both stores, with a legend and in-force counts per class. */
export function renderRuleMap(rs: RuleSet): string {
  const rows = [...rs.framework, ...rs.org].sort(compareRows);
  const counts = summariseRuleSet(rs);
  const total = CLASSES.reduce((n, k) => n + counts[k], 0);
  return [
    "<!-- GENERATED by `gov rules build` from framework/rules/rules.yaml and policies/rules.yaml — do not edit. -->",
    "",
    "# Rule map",
    "",
    "Every rule that governs this organization's agentic work — the framework's specification rules and the",
    `organization's policy rules (policy version ${rs.orgVersion}) — merged into one view. There is one row per`,
    "revision: a closed row shows when it stopped applying, the row with no End is in force, and a rule whose last",
    "row is closed has been retired. `Class` is derived from the row's checks and the catalog: what actually holds",
    "the rule up.",
    "",
    "## Classes",
    "",
    ...CLASSES.map((k) => `- **${k}** — ${RULE_CLASS_LEGEND[k]}`),
    "",
    `In force: ${total} rules — ${CLASSES.map((k) => `${k} ${counts[k]}`).join(" · ")}.`,
    "",
    "## Rules",
    "",
    "| Gov Rule | Document | Document Type | Section | Owner | Level | Expectation | Actor | Cue | Check | Class | Start | End |",
    "|---|---|---|---|---|---|---|---|---|---|---|---|---|",
    ...rows.map((r) => line(r, rs)),
    "",
  ].join("\n");
}
