// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Svayam Infoware Pvt. Ltd.
/**
 * THE `github-actions` RENDERER (rule-model-design.md Q14; W6).
 *
 * A binding is rendered into the resource's own automation — there is no central service. For GitHub that is ONE
 * workflow per repository, `.github/workflows/gov-checks.yml`, triggering on the union of the bound events, with
 * one job per rule · event that calls `gov check run <GOV-ID> --resource <r> --event <e>`. One job per rule makes
 * each rule its own status check, which is what a branch protection can require.
 *
 * BYTE-STABLE: triggers, issue types and jobs are sorted, and a rule bound twice on one event (two actions) is one
 * job — the runner runs every binding of that rule on that event. The same bindings in any order render the same
 * bytes, so a re-render that changes nothing produces no diff.
 *
 * An event GitHub Actions cannot trigger on is NOT dropped silently: it is named in a comment at the top, and the
 * rule stays `cannot-tell` for it.
 *
 * Pure.
 */
import type { CheckBinding } from "../model/catalog.js";
import type { BindingRenderer } from "../model/contracts.js";

export const WORKFLOW_PATH = ".github/workflows/gov-checks.yml";

export interface GithubRendererOptions {
  /** What `npm install -g` installs. Default: the published gov CLI, as `gov-validate.yml` installs it. */
  readonly govPackage?: string;
}

type Binding = { readonly id: string; readonly check: CheckBinding };
/** The GitHub trigger for a resource · event: the `on:` key, and for `issues` the activity type. */
type Trigger = { readonly on: string; readonly type?: string };

const ISSUE_TYPES = new Set(["opened", "closed", "edited"]);

function triggerFor(resource: string, event: string): Trigger | null {
  if (resource.startsWith("vcs.") && (event === "pull_request" || event === "push")) return { on: event };
  if (resource === "pms.issue" && ISSUE_TYPES.has(event)) return { on: "issues", type: event };
  return null;
}

const cmp = (a: string, b: string): number => (a < b ? -1 : a > b ? 1 : 0);
/** A GitHub job id: letters, digits, `_` and `-`, starting with a letter or `_`. */
const jobId = (s: string): string => {
  const t = s.replace(/[^A-Za-z0-9_-]/g, "_");
  return /^[A-Za-z_]/.test(t) ? t : `_${t}`;
};

/**
 * One workflow for every github-actions binding of one repository, across its resources (a gov repo is both
 * `vcs.gov-repo` and where `pms.issue` events fire). Returns [] when nothing is bound.
 */
export function renderWorkflow(bindings: readonly Binding[], opts: GithubRendererOptions = {}): { path: string; text: string }[] {
  const pkg = opts.govPackage ?? "@svayam-opensource/gov";
  const jobs = new Map<string, { id: string; resource: string; event: string; trigger: Trigger }>();
  const skipped = new Set<string>();
  for (const { id, check } of bindings) {
    const { resource, event } = check.on;
    const trigger = triggerFor(resource, event);
    if (!trigger) {
      skipped.add(`# not rendered: ${id} on ${resource} · ${event} — GitHub Actions has no trigger for it (cannot-tell)`);
      continue;
    }
    jobs.set(`${id}\u0000${resource}\u0000${event}`, { id, resource, event, trigger });
  }
  // Nothing GitHub can trigger on: no workflow (an `on:` with no events is not a valid one).
  if (!jobs.size) return [];

  const sorted = [...jobs.entries()].sort(([a], [b]) => cmp(a, b)).map(([, j]) => j);
  const on = new Map<string, Set<string>>();
  for (const j of sorted) {
    const types = on.get(j.trigger.on) ?? new Set<string>();
    if (j.trigger.type) types.add(j.trigger.type);
    on.set(j.trigger.on, types);
  }

  const lines: string[] = [
    "# GENERATED by gov from the rule stores — do not edit; re-render instead.",
    "# Each job runs one rule's checks for one event through `gov check run <GOV-ID>`. Rules are read from the",
    "# default branch, never from the branch under review.",
    "name: gov-checks",
    ...[...skipped].sort(cmp),
    "",
    "on:",
  ];
  for (const name of [...on.keys()].sort(cmp)) {
    lines.push(`  ${name}:`);
    const types = [...on.get(name)!].sort(cmp);
    if (types.length) lines.push(`    types: [${types.join(", ")}]`);
  }
  lines.push("", "permissions:", "  contents: read", "", "jobs:");
  for (const j of sorted) {
    const cond = j.trigger.type
      ? `github.event_name == '${j.trigger.on}' && github.event.action == '${j.trigger.type}'`
      : `github.event_name == '${j.trigger.on}'`;
    // Two resources of one repo bound on the same event name would share a job id; the resource keeps them apart.
    const sameName = sorted.filter((k) => k.id === j.id && k.event === j.event).length > 1;
    lines.push(
      `  ${jobId(sameName ? `${j.id}_${j.resource}_${j.event}` : `${j.id}_${j.event}`)}:`,
      `    name: ${j.id} · ${j.event}`,
      `    if: ${cond}`,
      "    runs-on: ubuntu-latest",
      "    timeout-minutes: 10",
      "    steps:",
      "      - uses: actions/checkout@v4",
      "        with:",
      "          fetch-depth: 0",
      "      - uses: actions/setup-node@v4",
      "        with:",
      '          node-version: "24"',
      "      - name: Install the gov CLI",
      `        run: npm install -g ${pkg}`,
      `      - name: gov check run ${j.id}`,
      `        run: gov check run ${j.id} --resource ${j.resource} --event ${j.event}`,
    );
  }
  return [{ path: WORKFLOW_PATH, text: lines.join("\n") + "\n" }];
}

export function githubActionsRenderer(opts: GithubRendererOptions = {}): BindingRenderer {
  return {
    renderer: "github-actions",
    render: (bindings) => renderWorkflow(bindings, opts),
  };
}
