// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Svayam Infoware Pvt. Ltd.
/**
 * THE LOCK ON DISK — and why it is JSON rather than YAML.
 *
 * gov carries exactly one runtime dependency and no YAML parser; `org-config.yaml` is read by a hand-rolled
 * scalar reader because a human writes it and it must stay readable. The lock is the opposite kind of file:
 * GENERATED, machine-owned, never hand-edited, and the one file where a parse that silently mis-reads an entry
 * would re-point a POL number at different text. So it is JSON — `JSON.parse` is exact, needs nothing, and
 * fails loudly on a file somebody edited by hand, which is the correct response to that edit.
 *
 * It stays append-only, and this module will not write an entry that removes or renumbers an existing one: the
 * whole purpose of the lock is that `POL-427` cited in gov's own source code three months ago still means what
 * it meant. `writeLock` therefore takes the OLD lock and refuses a write that would lose an entry.
 */
import { type PolLock, type PolEntry, formatPol, polNumber } from "./pol-lock.js";

/** The file gov reads and writes, beside the policies it locks. */
export const LOCK_FILE = ".pol-lock.json";

/** What a lock file looks like on disk. `version` is the FILE format, not the policy's. */
interface LockDoc {
  readonly version: 1;
  readonly note: string;
  readonly start: number;
  readonly entries: readonly PolEntry[];
}

const NOTE =
  "GENERATED by `gov rules build` — append-only. Never reorder, renumber or delete an entry: a POL number is "
  + "allocated once and cited forever, including in source code, so losing an entry silently re-points a "
  + "citation at different text. `start` is the first number NEW allocation may use.";

/**
 * Parse a lock file. A missing file is an EMPTY lock, not an error — the first `gov rules build` in a workspace
 * has nothing to read, and treating that as a failure would make the feature unusable exactly once per adopter.
 * A CORRUPT file is an error, because the alternative is allocating numbers on top of numbers we cannot see.
 */
export function parseLock(text: string | null, start: number): { lock?: PolLock; error?: string } {
  if (text === null || text.trim() === "") return { lock: { start, entries: [] } };
  let doc: unknown;
  try {
    doc = JSON.parse(text);
  } catch (e) {
    return { error: `${LOCK_FILE} is not valid JSON (${String(e)}). It is generated — restore it from git rather than editing it.` };
  }
  const d = doc as Partial<LockDoc>;
  if (!Array.isArray(d.entries)) return { error: `${LOCK_FILE} has no entries array — it is not a lock file.` };
  for (const e of d.entries) {
    if (!e.pol || !/^POL-\d{3}[a-z]?$/.test(e.pol)) return { error: `${LOCK_FILE} holds an entry with no valid pol: ${JSON.stringify(e)}` };
  }
  return { lock: { start: typeof d.start === "number" ? d.start : start, entries: d.entries } };
}

/** Serialise, sorted by number so a diff shows the change and not a reshuffle. */
export function renderLock(lock: PolLock): string {
  const entries = [...lock.entries].sort((a, b) => a.pol.localeCompare(b.pol));
  const doc: LockDoc = { version: 1, note: NOTE, start: lock.start, entries };
  return `${JSON.stringify(doc, null, 2)}\n`;
}

/**
 * The append-only guard. Returns the text to write, or the reason it must not be written.
 *
 * A lock that loses an entry is worse than a lock that never existed: the citation still resolves, to nothing or
 * to something else. So this compares against what was there and refuses, rather than trusting the caller to
 * have been careful.
 */
export function writeLock(previous: PolLock, next: PolLock): { text?: string; error?: string } {
  const had = new Map(previous.entries.map((e) => [e.pol, e]));
  const has = new Set(next.entries.map((e) => e.pol));
  const lost = [...had.keys()].filter((p) => !has.has(p));
  if (lost.length) {
    return { error: `refusing to write ${LOCK_FILE}: it would drop ${lost.join(", ")}. Retire a clause (which keeps its entry) rather than removing it.` };
  }
  if (next.start < previous.start) {
    return { error: `refusing to write ${LOCK_FILE}: start would move backwards (${previous.start} → ${next.start}), which would re-allocate numbers already issued.` };
  }
  return { text: renderLock(next) };
}

/**
 * Convert the interim YAML lock this project seeded by hand into the JSON one gov reads.
 *
 * Kept because the framework already SHIPPED `.pol-lock.yaml`, so an adopter who ran an earlier build has one on
 * disk. Reading it once and writing JSON is a migration; refusing to read it would strip every number the
 * framework had already allocated, which is the one outcome the lock exists to prevent. The parser is narrow on
 * purpose — it reads exactly the flat shape that seeding produced, and anything else is an error.
 */
export function parseLegacyYamlLock(text: string): { lock?: PolLock; error?: string } {
  const start = Number(/^start:\s*(\d+)/m.exec(text)?.[1] ?? NaN);
  if (!Number.isFinite(start)) return { error: "the legacy lock has no `start:` line" };
  const entries: PolEntry[] = [];
  for (const [, line] of text.matchAll(/^ {2}- (.+)$/gm)) {
    const e: Record<string, string | boolean> = {};
    for (const [, k, v] of line.matchAll(/(\w+): ("(?:[^"\\]|\\.)*"|true|false|\d+)/g)) {
      e[k] = v === "true" ? true : v === "false" ? false : v.startsWith('"') ? (JSON.parse(v) as string) : v;
    }
    if (typeof e.pol === "string") entries.push(e as unknown as PolEntry);
  }
  if (!entries.length) return { error: "the legacy lock has no entries" };
  return { lock: { start, entries } };
}

/** The highest number issued in this lock's own range — what a report prints as "next". */
export const nextFree = (lock: PolLock): string =>
  formatPol(Math.max(lock.start - 1, ...lock.entries.map((e) => polNumber(e.pol)).filter((n) => n < lock.start + 800)) + 1);
