#!/usr/bin/env bash
# Script: propose-knowledge
# Purpose: Ad-hoc org knowledge proposals outside any project context.
#          Used for initial bootstrap, policy updates, and standalone learnings.
# Usage:   bash propose-knowledge.sh <branch_slug> <description>
# Compliance: C02 — proposals require domain owner approval via PR (POL-107 to POL-109)

set -euo pipefail
source "$(dirname "$0")/lib.sh"
load_config

# ── Inputs ────────────────────────────────────────────────────────────────────

BRANCH_SLUG="${1:-}"
DESCRIPTION="${2:-}"
MODE="${3:-create}"   # create (default), --submit, --archive

[[ -n "$BRANCH_SLUG"  ]] || hard_stop "Usage: $0 <branch_slug> <description> [--submit|--archive]"
[[ -n "$DESCRIPTION"  ]] || hard_stop "Usage: $0 <branch_slug> <description> [--submit|--archive]"

case "$MODE" in
  create|--submit|--archive) ;;
  *) hard_stop "Unknown mode: $MODE (expected --submit or --archive)" ;;
esac

KNOWLEDGE_BRANCH="knowledge-$BRANCH_SLUG"

echo "=== propose-knowledge"
echo "    Branch:      $KNOWLEDGE_BRANCH"
echo "    Description: $DESCRIPTION"
echo "    Mode:        $MODE"
echo ""

cd "$REPO_ROOT"
git fetch origin "$DEFAULT_BRANCH" 2>/dev/null || true
git fetch origin "$KNOWLEDGE_BRANCH" 2>/dev/null || true

# ── Mode: create ──────────────────────────────────────────────────────────────

if [[ "$MODE" == "create" ]]; then
  if git rev-parse --verify "$KNOWLEDGE_BRANCH" &>/dev/null || \
     git ls-remote --exit-code origin "$KNOWLEDGE_BRANCH" &>/dev/null; then
    hard_stop "Branch '$KNOWLEDGE_BRANCH' already exists — investigate before proceeding."
  fi

  # Failure cleanup (#64): if branch creation/push fails part-way (e.g. push
  # rejected after the local branch exists), undo what we made so a re-run does
  # not hard-stop on "branch already exists". State flags gate each undo; the
  # trap is disarmed once create mode completes successfully.
  _PK_BRANCH_CREATED=false
  _PK_BRANCH_PUSHED=false
  _PK_DONE=false
  cleanup_on_failure() {
    local rc=$?
    $_PK_DONE && return 0
    [[ $rc -eq 0 ]] && return 0
    warn "propose-knowledge failed (exit $rc) — cleaning up so the run is re-runnable."
    if $_PK_BRANCH_CREATED; then
      git -C "$REPO_ROOT" checkout "$DEFAULT_BRANCH" &>/dev/null || true
      local scope="local"
      if $_PK_BRANCH_PUSHED; then
        git -C "$REPO_ROOT" push origin --delete "$KNOWLEDGE_BRANCH" &>/dev/null || true
        scope="local + remote"
      fi
      git -C "$REPO_ROOT" branch -D "$KNOWLEDGE_BRANCH" &>/dev/null || true
      info "Removed branch '$KNOWLEDGE_BRANCH' ($scope)."
    fi
  }
  trap cleanup_on_failure EXIT

  git checkout "$DEFAULT_BRANCH"
  git pull origin "$DEFAULT_BRANCH"
  git checkout -b "$KNOWLEDGE_BRANCH"
  _PK_BRANCH_CREATED=true
  git push -u origin "$KNOWLEDGE_BRANCH"
  _PK_BRANCH_PUSHED=true

  echo "Branch '$KNOWLEDGE_BRANCH' created."
  echo ""
  echo "=== Next: Author your knowledge changes"
  echo ""
  echo "    1. Edit or add files under knowledge/ on branch '$KNOWLEDGE_BRANCH'."
  echo "       - New content:     add to the owning domain's layer (see knowledge/README.md)"
  echo "       - Policy updates:  edit knowledge/policies/"
  echo "       - Patterns:        edit <domain>/patterns/"
  echo "       - Architecture:    edit knowledge/architecture/{system,data}/"
  echo ""
  echo "    2. Commit your changes:"
  echo "       git add knowledge/"
  echo "       git commit -m 'knowledge: $DESCRIPTION'"
  echo "       git push origin $KNOWLEDGE_BRANCH"
  echo ""
  echo "    3. Then create the PR:"
  echo "       bash propose-knowledge.sh $BRANCH_SLUG \"$DESCRIPTION\" --submit"
  echo ""
  # Success: branch is intentionally kept for the author — disarm cleanup.
  _PK_DONE=true
  exit 0
fi

# ── Mode: --submit / --archive — branch must already exist ───────────────────

if ! git rev-parse --verify "$KNOWLEDGE_BRANCH" &>/dev/null && \
   ! git ls-remote --exit-code origin "$KNOWLEDGE_BRANCH" &>/dev/null; then
  hard_stop "Branch '$KNOWLEDGE_BRANCH' does not exist. Run without --submit/--archive first to create it."
fi

if [[ "$MODE" == "--submit" ]]; then
  # ── Raise PR ────────────────────────────────────────────────────────────────
  echo "Creating PR: $KNOWLEDGE_BRANCH → $DEFAULT_BRANCH..."

  PR_BODY=$(cat <<MD
## Knowledge Proposal: $DESCRIPTION

**Branch:** \`$KNOWLEDGE_BRANCH\`
**Author:** $(git config user.email 2>/dev/null || echo "unknown")
**Date:** $(today)

### Summary

$DESCRIPTION

### Review Notes

- This is a manually authored knowledge proposal (no LLM synthesis).
- CODEOWNERS will auto-assign domain owners as reviewers based on folders touched.
- Once merged, CI/CD will regenerate static site and vector embeddings.

### Post-merge

Archive tag \`archive/$KNOWLEDGE_BRANCH\` will be created and branch deleted.

*Generated by propose-knowledge.sh*
MD
)

  PR_URL=$(gh pr create \
    --base "$DEFAULT_BRANCH" \
    --head "$KNOWLEDGE_BRANCH" \
    --title "[Knowledge Proposal] $DESCRIPTION" \
    --body "$PR_BODY" \
    2>/dev/null) \
    || {
      warn "PR creation failed — retrying..."
      PR_URL=$(gh pr create \
        --base "$DEFAULT_BRANCH" \
        --head "$KNOWLEDGE_BRANCH" \
        --title "[Knowledge Proposal] $DESCRIPTION" \
        --body "$PR_BODY")
    }

  echo ""
  echo "=== PR created: $PR_URL"
  echo "    CODEOWNERS will auto-assign domain reviewers."
  echo ""
  echo "    After merge, archive the branch:"
  echo "    bash propose-knowledge.sh $BRANCH_SLUG \"$DESCRIPTION\" --archive"
fi

if [[ "$MODE" == "--archive" ]]; then
  # ── Archive after merge ──────────────────────────────────────────────────────
  git fetch origin "$DEFAULT_BRANCH"
  git checkout "$DEFAULT_BRANCH"
  git pull origin "$DEFAULT_BRANCH"
  archive_branch "$REPO_ROOT" "$KNOWLEDGE_BRANCH"
  echo ""
  echo "=== Branch archived: archive/$KNOWLEDGE_BRANCH"
fi
